def display_instructions():
    print("Welcome to 'Hunt the Wumpus'")
    print("  The wumpus lives in a cave of 20 rooms. each room")
    print("has 3 tunnels leading to other rooms. (Look at a")
    print("dodecahedron to see how this works-if you don't know")
    print("what a dodecahedron is, ask someone)")
    print()
    print("     Hazards:")
    print(" Bottomless pits - Two rooms have bottomless pits in them")
    print("     if you go there, you fall into the pit (& lose!)")
    print(" Super bats - Two other rooms have super bats. If you")
    print("     go there, a bat grabs you and takes you to some other")
    print("     room at random. (Which might be troublesome)")
    print()
    print("     Wumpus:")
    print(" The wumpus is not bothered by the hazards (he has sucker")
    print(" feet and is too big for a bat to lift).  Usually")
    print(" he is asleep. Two things wake him up: your entering")
    print(" his room or your shooting an arrow.")
    print("     If the wumpus wakes, he moves (p=.75) one room")
    print(" or stays still (p=.25). After that, if he is where you")
    print(" are, he eats you up (& you lose!)")
    print()
    print("     You:")
    print(" Each turn you may move or shoot a crooked arrow")
    print("   moving: you can go one room (thru one tunnel)")
    print("   arrows: you have 5 arrows. You lose when you run out.")
    print("   each arrow can go from 1 to 5 rooms. You aim by telling")
    print("   the computer the room#s you want the arrow to go to.")
    print("   If the arrow can't go that way (ie no tunnel) it moves")
    print("   at ramdom to the next room.")
    print("     If the arrow hits the wumpus, you win.")
    print("     If the arrow hits you, you lose.")
    print()
    print("    Warnings:")
    print("     When you are one room away from wumpus or hazard,")
    print("    the computer says:")
    print(" Wumpus -  'I smell a wumpus'")
    print(" Bat    -  'Bats nearby'")
    print(" Pit    -  'I feel a draft'")
    print()


def main():
    i = input("Instructions (y/n)? ")
    if i == "y":
        display_instructions()


if __name__ == "__main__":
    main()
